import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'Dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'aubitWallet',
        path: '',
        title: 'Aubit Wallet',
        translateKey: 'Aubit Wallet',
        icon: 'aubitWallet',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [],
    },
    {
        key: 'assets',
        path: '/assets',
        title: 'Assets',
        translateKey: 'Assets',
        icon: 'assets',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'marketplace',
        path: '/marketplace',
        title: 'Marketplace',
        translateKey: 'Marketplace',
        icon: 'marketplace',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'mint',
        path: '/mint',
        title: 'Mint',
        translateKey: 'Mint',
        icon: 'mint',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'sell',
        path: '/sell',
        title: 'Sell',
        translateKey: 'Sell',
        icon: 'sell',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'claims',
        path: '/claims',
        title: 'Claims',
        translateKey: 'Claims',
        icon: 'claims',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'importContract',
        path: '/import-contract',
        title: 'Import Contract',
        translateKey: 'Import Contract',
        icon: 'importContract',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'walletSettings',
        path: '/wallet-settings',
        title: 'Wallet Settings',
        translateKey: 'Wallet Settings',
        icon: 'walletSettings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'validateAubit',
        path: '/validate-aubit',
        title: 'Validate AuBit',
        translateKey: 'Validate AuBit',
        icon: 'validateAubit',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'store',
        path: '/store',
        title: 'Store',
        translateKey: 'Store',
        icon: 'store',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'inventory',
        path: '/inventory',
        title: 'Inventory',
        translateKey: 'Inventory',
        icon: 'inventory',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'orders',
        path: '/orders',
        title: 'Orders',
        translateKey: 'Orders',
        icon: 'orders',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'rewardProgram',
        path: '',
        title: 'Reward Program',
        translateKey: 'Reward Program',
        icon: 'rewardProgram',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [],
    },
    {
        key: 'overview',
        path: '/overview',
        title: 'Overview',
        translateKey: 'Overview',
        icon: 'overview',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'earnings',
        path: '/earnings',
        title: 'Earnings',
        translateKey: 'Earnings',
        icon: 'earnings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'yieldHub',
        path: '/yield-hub',
        title: 'Yield Hub',
        translateKey: 'Yield Hub',
        icon: 'yieldHub',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'sales',
        path: '/sales',
        title: 'Sales',
        translateKey: 'Sales',
        icon: 'sales',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'team',
        path: '/team',
        title: 'Team',
        translateKey: 'Team',
        icon: 'team',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'leaderboards',
        path: '/leaderboards',
        title: 'Leaderboards',
        translateKey: 'Leaderboards',
        icon: 'leaderboards',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'tools',
        path: '/tools',
        title: 'Tools',
        translateKey: 'Tools',
        icon: 'tools',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'starvara',
        path: '/starvara',
        title: 'Starvara',
        translateKey: 'Starvara',
        icon: 'starvara',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'news',
        path: '/news',
        title: 'News',
        translateKey: 'News',
        icon: 'news',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'support',
        path: '/support',
        title: 'Support',
        translateKey: 'Support',
        icon: 'support',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
]

export default navigationConfig
